import os
import argparse
from keyczar import keyczar
from rrg.billing import cache_non_date_parsed as routine
from rrg.models import Contract
from rrg.models import session_maker

parser = argparse.ArgumentParser(description='RRG Cache Contracts')

parser.add_argument(
    '--datadir', required=True,
    help='datadir dir',
    default='/php-apps/cake.rocketsredglare.com/rrg/data/')


parser.add_argument(
    '--keyczardir', required=True,
    help='dir of encryption keys generated by keyczart',
    default='/.keyczar')
parser.add_argument('--db-user', required=True, help='database user', default='marcdba')
parser.add_argument('--mysql-host', required=True, help='database host - MYSQL_PORT_3306_TCP_ADDR', default='marcdba')
parser.add_argument('--mysql-port', required=True, help='database port - MYSQL_PORT_3306_TCP_PORT', default=3306)
parser.add_argument('--db', required=True, help='d', default='rrg')
parser.add_argument('--db-pass', required=True, help='database pw', default='deadbeef')


def cache_contracts():
    """
    replaces cake cache_clients
    :param data_dir:
    :return:
    """
    args = parser.parse_args()
    session = session_maker(args)
    crypter = keyczar.Crypter.Read(args.keyczardir)
    print('Caching Contracts %s into %s' % (args.db, os.path.join(args.datadir, 'contracts')))
    routine(session, os.path.join(args.datadir, 'contracts'), Contract, crypter)
    session.commit()
